//------------------------------------------------------------------------------------------
CREATE TABLE TBEMPRESA(
CDEMPRESA VARCHAR(20) NOT NULL,
NMEMRPESA VARCHAR(100),
NUCNPJ varchar(20),
NUTELEFONE DECIMAL(11)
PRIMARY KEY(CDEMPRESA)
);
//------------------------------------------------------------------------------------------
CREATE TABLE TBCLIENTE(
CDEMPRESA VARCHAR(20) NOT NULL,
CDCLIENTE VARCHAR(20) NOT NULL,
NMCLIENTE varchar(100),
NUCPF DECIMAL(11),
primary key(CDEMPRESA, CDCLIENTE),
CONSTRAINT FK_TBEMPRESA_TBCLIENTE FOREIGN KEY(CDEMPRESA) REFERENCES TBEMPRESA(CDEMPRESA)
);

//------------------------------------------------------------------------------------------
CREATE TABLE TBFUNCIONARIO(
CDEMPRESA varchar(20) NOT NULL,
CDFUNCIONARIO varchar(20) NOT NULL,
NMFUNCIONARIO varchar(100),
NUCPF varchar(20),
NUTELEFONE DECIMAL(11),
VLSALARIO DECIMAL(5,2),
PRIMARY KEY (CDEMPRESA, CDFUNCIONARIO),
CONSTRAINT FK_TBEMPRESA_TBFUNCIONARIO FOREIGN KEY(CDEMPRESA) REFERENCES TBEMPRESA(CDEMPRESA)
);
//------------------------------------------------------------------------------------------
CREATE TABLE TBPRODUTO(
CDEMPRESA varchar(20) NOT NULL,
CDPRODUTO VARCHAR(20) NOT NULL,
NMPRODUTO VARCHAR(100),
DSPRODUTO VARCHAR(500),
VLPRODUTO DECIMAL (5,2),
PRIMARY KEY(CDEMPRESA, CDPRODUTO),
CONSTRAINT FK_TBEMPRESA_TBPRODUTO FOREIGN KEY (CDEMPRESA) REFERENCES TBEMPRESA(CDEMPRESA)
);
//------------------------------------------------------------------------------------------
CREATE TABLE TBESTOQUE(
CDEMPRESA varchar(20) NOT NULL,
CDPRODUTO varchar(20) NOT NULL,
CDESTOQUE varchar(20) NOT NULL,
QTESTOQUE DECIMAL (9),
QTESTOQUERESERVADO DECIMAL(9),
primary key(CDEMPRESA, CDPRODUTO,CDESTOQUE),
constraint FK_TBEMPRESA_TBESTOQUE foreign key(CDEMPRESA) REFERENCES TBEMPRESA (CDEMPRESA),
constraint FK_TBPRODUTO_TBESTOQUE foreign key(CDEMPRESA,CDPRODUTO)
REFERENCES TBPRODUTO(CDEMPRESA, CDPRODUTO)
);
//------------------------------------------------------------------------------------------
INSERT INTO TBEMPRESA (CDEMPRESA, NMEMPRESA, NUCNPJ, NUTELEFONE)
VALUES ('1','Farmacia Irineu','00.000/0001-65','21999219090');
INSERT INTO TBEMPRESA (CDEMPRESA, NMEMPRESA, NUCNPJ, NUTELEFONE)
VALUES ('2','Farmacia Jubileu','00.000/0001-65','21999219090');
INSERT INTO TBEMPRESA (CDEMPRESA, NMEMPRESA, NUCNPJ, NUTELEFONE)
VALUES ('3','Farmacia tadeu','00.000/0001-65','21999219090');
INSERT INTO TBEMPRESA (CDEMPRESA, NMEMPRESA, NUCNPJ, NUTELEFONE)
VALUES ('4','Farmacia leleu','00.000/0001-65','21999219090');
INSERT INTO TBEMPRESA (CDEMPRESA, NMEMPRESA, NUCNPJ, NUTELEFONE)
VALUES ('5','Farmacia Bartolomeu','00.000/0001-65','21999219090');
USE FARMACIA;
//------------------------------------------------------------------------------------------
SELECT * FROM TBEMPRESA;

USE FARMACIA;
//------------------------------------------------------------------------------------------